### ISSUE TITLE
Matomo Integration

### ISSUE THREAD

**Issue by woolfg** [EngineeringKiosk/webpage#18]
- [x] Create Matomo account (piwik.inlupus.at)
- [x] Integrate Matomo code in webpage
- [ ] Add custom events to player, including timemarker jumps

**Comment by woolfg** [comment]
```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(["setDoNotTrack", true]);
  _paq.push(["disableCookies"]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://piwik.inlupus.at/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '18']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="https://piwik.inlupus.at/matomo.php?idsite=18&amp;rec=1" style="border:0;" alt="" /></p></noscript>
<!-- End Matomo Code -->
```

**Comment by woolfg** [comment]
docs for the js api and the function `trackEvent` can be found at https://developer.matomo.org/api-reference/tracking-javascript

**Comment by andygrunwald** [comment]
Matomo is integrated into the page.

To enable click tracker for chapter marks inside the player, it seems that we
* need to fork the player
* Add our modificatoin
* compile it again

Because we are not able to add our own click handler, see https://github.com/podigee/podigee-podcast-player/blob/master/src/javascripts/extensions/chaptermarks.coffee#L63-L66

**Comment by woolfg** [comment]
or we do it the dirty JS way and call the following code after the player was loaded (maybe we can get an event there? otherwise we have to check for some time if the code is already there:

```chaptersmarks = document.getElementsByClassName("chaptermark");
Array.prototype.forEach.call(chaptersmarks, e => e.addEventListener("click",function () { console.log("clicked and call the event here then...") } ))```

**Comment by andygrunwald** [comment]
Wanted:
* player events
* chapter events

**Comment by andygrunwald** [comment]
Current status:

I forked the [podigee/podigee-podcast-player](https://github.com/podigee/podigee-podcast-player/) into [EngineeringKiosk/podigee-podcast-player](https://github.com/EngineeringKiosk/podigee-podcast-player). Main purpose was to be able to self-compile it and integrate it from the local project rather from Podigee itself.

While doing so, I found out that podigee/podigee-podcast-player implements the http://playerjs.io/ spec via [embedly/player.js](https://github.com/embedly/player.js). See 
* [Playerjs-spec](https://github.com/embedly/player.js/blob/master/SPEC.rst)
* [Podigee Player Playerjs Adapter](https://github.com/podigee/podigee-podcast-player/blob/master/src/javascripts/extensions/playerjs/adapter.coffee)

In https://github.com/EngineeringKiosk/webpage/pull/81/files#diff-1f17be1ad22cddc1e0bfcf3389eaba97c2bdde4df4434641e699a4c806424a34 I integrated the first basic version and it is working.

The player fork is still needed because the hosted podigee have some issues with the readyness of the playerjs spec, see https://github.com/podigee/podigee-podcast-player/issues/102.
While testing it, I got the same problem like described in the ticket
